### PR TITLE
Endless head

### LINKED ISSUE #28: Endless HEAD request ?
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | v1.0.0

#### Actual Behavior

A `HEAD` request is endless.

#### Expected Behavior

I expect that the `HEAD` request to end and to get a response

#### Steps to Reproduce

Reproducible with this melody script https://github.com/sensiolabs/melody

The guzzle http client has the expected behavior, using the http adapter, the head request doesn't end.

```
<?php
<<<CONFIG
packages:
    - "php-http/guzzle5-adapter"
    - "guzzlehttp/psr7"
    - "php-http/message"
CONFIG;

use GuzzleHttp\Client as GuzzleClient;
use Http\Adapter\Guzzle5\Client as GuzzleAdapter;
use Http\Message\MessageFactory\GuzzleMessageFactory;
use Http\Message\Formatter\SimpleFormatter;

$guzzle = new GuzzleClient([]);

$request = $guzzle->createRequest('HEAD', 'http://example.com');
echo "send...\n\n";
$response = $guzzle->send($request);
echo "\n\nend guzzle...\n\n";

$messageFactory = new GuzzleMessageFactory();
$adapter = new GuzzleAdapter($guzzle, $messageFactory);

$request = $messageFactory->createRequest('HEAD', 'http://example.com');
echo "send...\n\n";
$response = $adapter->sendRequest($request);
echo (new SimpleFormatter())->formatRequest($request);
echo "\n\nend\n\n";
```

#### Possible Solutions

Maybe, it could be resolved by modifing the `src/Client.php:76`:
```
$options['body'] = '' === (string) $request->getBody() ? null : (string) $request->getBody()
```

### PR DESCRIPTION
**Pull request by aaa2000**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| BC breaks?      | maybe
| Deprecations?   | no
| Related tickets | fixes #28 
| License         | MIT

#### What's in this PR?

Fix the send of a `HEAD` request with the curl handler.

#### Why?

At present, the `HEAD` request does not end. The stream handler don't have this behaviour and the PHP Built-in web server don't show this behaviour. For the moment, the test use a remote url.

The guzzle6-adapter has not this issue.

#### Example Usage

See example of #28

#### Checklist

- [x] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix

#### To Do

- [ ] Replace the remote url in test

### CODE REVIEW

File: src/Client.php [hunk 1]
```diff
@@ -72,7 +72,7 @@ private function createRequest(RequestInterface $request)
 
         $options['version'] = $request->getProtocolVersion();
         $options['headers'] = $request->getHeaders();
-        $options['body'] = (string) $request->getBody();
+        $options['body'] = '' === (string) $request->getBody() ? null : (string) $request->getBody();
```
Comment (Nyholm) [inline src/Client.php]: Maybe this is easier to read?
```php
$body = (string) $request->getBody();
$options['body'] = '' === $body ? null : $body;
```

**Review by Nyholm — APPROVED** [review]
Thank you for this PR. 

I made a small comment, what do you think?

File: src/Client.php (hunk 1 above)
Comment (aaa2000) [reply src/Client.php]: Indeed, it is easier to read. Fix, squash and add a changelog item. Using a remote url in test is not a problem ?

**Comment by Nyholm** [comment]
No issue
